### ISSUE TITLE
Parser fails on differently formatted options

### ISSUE THREAD

**Issue by bobak** [tinganho/l10ns#111]
The parser fails to parse our formatting style, we require properties to be lined up which means they have usually one space before the colon.

Failing example:
```javascript
l('TRANSLATION_KEY', {
  gender : 'male',
  type   : 'animal'
});
```

Running `l10ns update` gives me this cryptic error message:
```bash
SHELL> l10ns update

/.nvm/v0.10.38/lib/node_modules/l10ns/libraries/parser.js:46
    obj[i] = language.LOCALIZATION_VARIABLE_NAME_SYNTAX.exec(obj[i])[1];
                                                                    ^
TypeError: Cannot read property '1' of null
    at Parser.getVariables (/.nvm/v0.10.38/lib/node_modules/l10ns/libraries/parser.js:46:69)
    at /.nvm/v0.10.38/lib/node_modules/l10ns/libraries/update.js:135:36
    at Array.forEach (native)
    at /.nvm/v0.10.38/lib/node_modules/l10ns/libraries/update.js:133:17
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
```

**Comment by tinganho** [comment]
@bobak thanks for reporting this. This is now fixed and published. Please just run a new `npm install l10ns -g` to get the changes.

**Comment by bobak** [comment]
Thanks for the quick turnaround, fix confirmed.

**Comment by sukazavr** [comment]
This issue is still actual, but this time for ES6 Object Notation.
I use 2.3.1 version.

Failing example:
```js
let btnShowNewDatasets = l('Datasets → Show New Btn', { lengthQueue })
```

Running `l10ns update` gives me this cryptic error message:
```cmd
C:\nvm\v5.3.0\node_modules\l10ns\libraries\parser.js:44
  for(var i = 0; i < obj.length; i++) {
                        ^

TypeError: Cannot read property 'length' of null
    at Parser.getVariables (C:\nvm\v5.3.0\node_modules\l10ns\libraries\parser.js:44:25)
    at C:\nvm\v5.3.0\node_modules\l10ns\libraries\update.js:135:36
    at Array.forEach (native)
    at C:\nvm\v5.3.0\node_modules\l10ns\libraries\update.js:133:17
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

**Comment by tinganho** [comment]
@sukazavr ES6 Object notation is not supported. Keep in mind it just uses simple regexes to parse out the message string. So it doesn't have any understanding of your code. This is an architectual design decision I took early. If we implemented a parser it would mean full time maintenance for me ot keep upto date with different parsers.

**Comment by qborreda** [comment]
@tinganho - what would be a good approach to overcome this?
I'm playing with the idea, not so efficient, of having a `localize_this.js` file within the `localization/` folder with just all the calls to `l('STRING_ID')` and make l10ns only parse that one. It seems to work on my react es6 environment, but can't parse the strings from the code as in @sukazavr case ..

**Comment by tinganho** [comment]
L10ns currently makes a few extractions steps. It uses regexes like this one https://github.com/tinganho/l10ns/tree/master/plugins/javascript/specifications#L106-L123. To get the variables.

This info together with @sukazavr stack trace should probably give you enough info to submit a PR.
